name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  cov:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.9.0'
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update apt repositories
        run: sudo apt update

      - name: Install apt packages
        run: |
            sudo apt install ocl-icd-opencl-dev
            sudo apt-get install -y libhwloc-dev

      # TODO enable when protoc needed again
      # - name: Install Protoc
      #   uses: arduino/setup-protoc@master
      #   with:
      #     version: "3.9.1"

      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Pull submodules
        run: git submodule update --init

      - name: Run all unit tests
        run: make test

      - name: Run test vectors
        run: make run-vectors

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check license headers
        run: make license

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Update apt repositories
        run: sudo apt update

      - name: Install OpenCL
        run: sudo apt install ocl-icd-opencl-dev

      # - name: Install Protoc
      #   uses: arduino/setup-protoc@master
      #   with:
      #     version: "3.9.1"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Check forest binary
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: -p forest

  # publish_docs:
  #   if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
  #   name: Publish Documentation
  #   needs: [clippy, test]
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: "recursive"

  #     - name: Install Rust
  #       run: rustup update beta && rustup default beta

  #     - name: Update apt repositories
  #       run: sudo apt update

  #     - name: Install OpenCL
  #       run: sudo apt install ocl-icd-opencl-dev

  #     # - name: Install Protoc
  #     #   uses: arduino/setup-protoc@master
  #     #   with:
  #     #     version: "3.9.1"

  #     - name: Build documentation
  #       run: cargo doc --no-deps --all-features
  #     - name: Publish documentation
  #       run: |
  #         cd target/doc
  #         git init
  #         echo '<meta http-equiv="refresh" content="0; url=https://chainsafe.github.io/forest/forest_vm/index.html">' > index.html
  #         git add .
  #         git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation'
  #         git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
